name: Build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: docker buildx create --driver docker-container --use
      - run: >
          docker buildx build
          --platform=linux/x86_64,linux/i386,linux/aarch64,linux/arm/v7
          --target artifact
          -o out
          --cache-to type=gha
          --cache-from type=gha
          --file Dockerfile.linux
          .

      - uses: actions/upload-artifact@v3
        with:
          name: linux
          path: out/*


  build-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./build_darwin.sh
      - uses: actions/upload-artifact@v3
        with:
          name: darwin
          path: ./out/*

  release:
    needs: [build-linux, build-darwin]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/download-artifact@v3
      - name: Create Release
        if: github.ref_name == 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          version="$(date --utc +%Y-%m-%d)-${{ github.event.pull_request.head.sha || github.sha }}"
          tag="build-${version}"
          if gh release view "${tag}" > /dev/null; then
            gh release upload "${tag}" **/*
          else
            gh release create --prerelease --title "Build ${version}" "${tag}" **/*
          fi
